# Generated by Django 4.2.7 on 2023-11-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_options_alter_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Achat', 'verbose_name_plural': 'Achats'},
        ),
    ]
