# Generated by Django 4.2.7 on 2023-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profitability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('type', models.CharField(default='sales', max_length=20, verbose_name='type')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Profitability',
                'verbose_name_plural': 'Profitability',
                'db_table': 'profitability_view',
                'managed': False,
            },
        ),
    ]
