# Generated by Django 4.2.7 on 2023-11-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_client_alter_sale_date_alter_sale_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
    ]
